[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/callback"
  [headers.values]
    Access-Control-Allow-Origin = "https://memberz.netlify.app"

[functions."cleanup"]
  schedule = "*/5 * * * *"
